Enumeration
Vishnu-M/lua-c-parser pull request #1
Opened 2019-07-25 15:54 UTC by Vishnu-M

2019-07-26 12:52 UTC, gligneul requested changes

2019-07-26 12:52 UTC, gligneul commented on main.lua
> +local declarations = {}
Usually people names this table the name of the module. In your case, you could name it cparser.
```suggestion
local cparser = {}
```
Also, rename the file to something like cparser.lua.
Another thing: I would remove the comment in the previous line.

2019-07-26 12:52 UTC, gligneul commented on main.lua
> +enum_child_visitor = function (cursor, parent)
You could use the usual syntax:
```suggestion
function enum_child_visitor(cursor, parent)
```

2019-07-26 12:52 UTC, gligneul commented on main.lua
> +parser = lib.newParser("check.c")
You should create a function that receives the input file, creates the parser, creates the output table and returns it. Then, create a busted file to test it.

2019-07-26 12:52 UTC, gligneul commented on main.lua
> +        --table containing contents of a single EnumDecl
Avoid comments that are descriptive; instead, only keep comments that explain what the code does. Usually, if your code is well written even explanatory comments are unnecessary. Descriptive comments are fine when you are coding to help you guide yourself, but most of the time you should remove then before committing.

2019-07-26 12:52 UTC, gligneul commented on main.lua
> +        kind = cursor:getKind();
```suggestion
        local kind = cursor:getKind()
```

2019-07-26 12:52 UTC, gligneul commented on main.lua
> +local enum_decl
We shouldn't use global variables to represent these. Ideally, we should pass these variables as parameters to the enum_handler. To do so, we need to modify `enum_handler` to forward the extra parameters it receives to the visitor.
The Lua code will look like:
```
local function my_handler(cursor, parent, my_table)
-- ...
end

local my_table = {}
cursor:visitChildren(ny_handler, my_table)
```

2019-07-26 12:52 UTC, gligneul commented on main.lua
> +        declarations[#declarations+1] = enum_decl
I prefer using `table.insert` so you don't have to repeat the array name twice.

2019-07-26 13:18 UTC, Vishnu-M commented on main.lua
> +parser = lib.newParser("check.c")
Ok, I was just checking in the beginning. Will do it.

2019-07-27 20:47 UTC, gligneul requested changes

2019-07-27 20:47 UTC, gligneul commented on cparser.lua
> +        func_decl.tag = 'function'
I feel that the code would look a little less cluttered if you use a table initializer:
```
local decl = { -- the func_ prefix is a bit redundant given that you are in the function_handler already
  tag = 'function',
  name = cursor:getSpelling(),
  inline = ...
  storage_specifier = ...
}
```

2019-07-27 20:47 UTC, gligneul commented on cparser.lua
> +        func_decl["return"] = return_type:getSpelling()
I would shorten return to ret just to avoid the clash with the reserved word.
```suggestion
        decl.ret = return_type:getSpelling()
```

2019-07-27 20:47 UTC, gligneul commented on cparser.lua
> +        for i=0, num_params-1 do
This is very strange in the Lua world, we should change the getArgCursor to be 1-based instead of 0-based.

2019-07-27 20:47 UTC, gligneul commented on cparser.lua
> +        local param
You can declare this inside the for loop.

2019-07-27 20:47 UTC, gligneul commented on cparser.lua
> +local function enum_child_visitor(cursor, parent, enum_fields)
I would write this function as an anonymous function inside `enum_handler`
```
cursor:visitChildren(function(cursor, parent)
end)

2019-07-27 20:47 UTC, gligneul commented on cparser.lua
> +        return "recurse"
I think you can use `continue` instead of `recurse` and call `getEnumValue` directly.
The function `getEnumValue` should return nil if there is no enum value.

2019-07-28 10:14 UTC, Vishnu-M commented on cparser.lua
> +        return "recurse"
@gligneul The problem is that the associated clang function returns value even when for `EnumConstantDecl` that doesn't have an integral value. We can't return `nil` in any case.
For example, 

`enum foo{a, b=11, c, d};`

corresponding enum values are : 

`a=0, b=11, c=12, d=13`

2019-07-28 12:24 UTC, gligneul commented on cparser.lua
> +        return "recurse"
In fact that is not an issue, computing the value for every enum declaration would be better.

2019-07-28 13:44 UTC, Vishnu-M commented on cparser.lua
> +        return "recurse"
Okay.

2019-07-28 14:26 UTC, gligneul commented on cparser.lua
> +        cursor:visitChildren(function (cursor, parent, fields)
Given that this function is now inlined, you don't need to pass the fields as a parameter.
```suggestion
        cursor:visitChildren(function (cursor, parent)
```

2019-07-28 14:27 UTC, gligneul approved these changes

2019-07-28 15:57 UTC, merged