StructDecl, UnionDecl and VarDecl
Vishnu-M/lua-c-parser pull request #4
Opened 2019-07-31 20:40 UTC by Vishnu-M

[WIP] - For preliminary comments. 
NB : Will merge only after adding tests.

2019-07-31 20:44 UTC, Vishnu-M commented on cparser.lua
> +        local definition = {}
Ignore this @gligneul .

2019-07-31 22:05 UTC, gligneul requested changes

2019-07-31 22:05 UTC, gligneul commented on cparser.lua
> +        cursor:visitChildren(function (cursor, _)
In this case you can suppress the parameter given that you don't have a third one.
```suggestion
        cursor:visitChildren(function (cursor)
```

2019-07-31 22:05 UTC, gligneul commented on cparser.lua
> +        if cursor:getKind() == "StructDecl" then
This is a nice place to use Lua ternary operator
```suggestion
        local tag = cursor:getKind() == "StructDecl" and 'struct' or 'union'
```

2019-07-31 22:05 UTC, gligneul commented on cparser.lua
> +        local decl = {
I think you should create the declaration in the end just like the other handlers.

2019-07-31 22:05 UTC, gligneul commented on cparser.lua
> +        local definition = {}
I would rename it to be consistent with the current vocabulary that we are using. e.g. Clang calls struct definitions StructDecl.
```suggestion
        local chield_declarations = {}
```
Another option would be inserting all declarations in the top-level. This option might be better even though we lose a bit of info.

2019-07-31 22:05 UTC, gligneul commented on cparser.lua
> +        cursor:visitChildren(function (cursor, _)
```suggestion
        cursor:visitChildren(function (cursor)
```

2019-08-01 18:45 UTC, gligneul approved these changes

2019-08-03 04:02 UTC, merged